import { CourseLevel, CourseStatus } from "@prisma/client";

export type SeedCategory = {
  id: string;
  name: string;
  slug: string;
  description: string;
};

export const CATEGORIES: SeedCategory[] = [
  {
    id: "cat_programming",
    name: "Programming",
    slug: "programming",
    description: "Pengembangan web, mobile, dan rekayasa perangkat lunak.",
  },
  {
    id: "cat_design",
    name: "Design",
    slug: "design",
    description: "UI/UX, desain produk, dan design system.",
  },
  {
    id: "cat_business",
    name: "Business",
    slug: "business",
    description: "Kewirausahaan, pemasaran, dan manajemen.",
  },
  {
    id: "cat_data",
    name: "Data & Analytics",
    slug: "data-analytics",
    description: "Analisis data, SQL, dan visualisasi.",
  },
  {
    id: "cat_personal",
    name: "Personal Development",
    slug: "personal-development",
    description: "Produktivitas, karier, dan soft skill.",
  },
  {
    id: "cat_ai",
    name: "AI & Machine Learning",
    slug: "ai-ml",
    description: "LLM, machine learning, dan rekayasa sistem AI.",
  },
  {
    id: "cat_prodeng",
    name: "Product & Engineering",
    slug: "product-engineering",
    description: "System design, keamanan aplikasi, dan praktik engineering.",
  },
];

export type SeedInstructor = {
  id: string;
  email: string;
  name: string;
  headline: string;
  expertiseSlug: string;
  bio: string;
};

export const INSTRUCTORS: SeedInstructor[] = [
  // Programming
  {
    id: "user_instructor",
    email: "instructor@example.com",
    name: "Budi Santoso",
    headline: "Software engineer | React & Next.js specialist",
    expertiseSlug: "programming",
    bio: "Software engineer dengan 10+ tahun pengalaman membangun aplikasi web. Fokus pada JavaScript, TypeScript, dan ekosistem React/Next.js.",
  },
  {
    id: "user_instructor_5",
    email: "instructor5@example.com",
    name: "Dewi Lestari",
    headline: "Backend engineer | Go & distributed systems",
    expertiseSlug: "programming",
    bio: "Backend engineer yang fokus pada sistem skala besar. Berpengalaman merancang API dan arsitektur microservices yang andal.",
  },
  {
    id: "user_instructor_6",
    email: "instructor6@example.com",
    name: "Raka Putra",
    headline: "Mobile developer | Flutter & Kotlin",
    expertiseSlug: "programming",
    bio: "Mobile developer yang sudah merilis puluhan aplikasi di Play Store dan App Store. Senang berbagi soal performa dan UX mobile.",
  },
  // Design
  {
    id: "user_instructor_2",
    email: "instructor2@example.com",
    name: "Sarah Wijaya",
    headline: "Product designer | UX & design systems",
    expertiseSlug: "design",
    bio: "Product designer yang sudah memimpin desain di beberapa startup. Senang membahas UX research, design system, dan workflow Figma.",
  },
  {
    id: "user_instructor_7",
    email: "instructor7@example.com",
    name: "Maya Anggraini",
    headline: "Brand & visual designer",
    expertiseSlug: "design",
    bio: "Visual designer dengan latar agency. Membantu brand membangun identitas visual yang konsisten dari logo hingga UI.",
  },
  // Data & Analytics
  {
    id: "user_instructor_3",
    email: "instructor3@example.com",
    name: "Andi Pratama",
    headline: "Data analyst & BI consultant",
    expertiseSlug: "data-analytics",
    bio: "Data analyst dan konsultan BI. Terbiasa mengolah data dengan SQL dan spreadsheet, lalu menyajikannya jadi insight yang actionable.",
  },
  {
    id: "user_instructor_8",
    email: "instructor8@example.com",
    name: "Fajar Nugroho",
    headline: "ML engineer | Python & data pipelines",
    expertiseSlug: "data-analytics",
    bio: "Machine learning engineer yang membangun data pipeline dan model di produksi. Fokus pada Python dan praktik MLOps.",
  },
  {
    id: "user_instructor_9",
    email: "instructor9@example.com",
    name: "Nadia Sari",
    headline: "Data scientist | statistik & visualisasi",
    expertiseSlug: "data-analytics",
    bio: "Data scientist dengan latar statistik. Suka menerjemahkan angka jadi cerita lewat visualisasi yang jelas.",
  },
  // Business
  {
    id: "user_instructor_4",
    email: "instructor4@example.com",
    name: "Rina Kusuma",
    headline: "Digital marketing & product strategist",
    expertiseSlug: "business",
    bio: "Praktisi digital marketing dan product management. Membantu banyak UMKM tumbuh lewat strategi pemasaran yang terukur.",
  },
  {
    id: "user_instructor_10",
    email: "instructor10@example.com",
    name: "Hendra Wijaya",
    headline: "Startup founder & growth strategist",
    expertiseSlug: "business",
    bio: "Founder yang sudah membangun dan menjual beberapa startup. Berbagi soal validasi ide, growth, dan operasional bisnis awal.",
  },
  // Personal Development
  {
    id: "user_instructor_11",
    email: "instructor11@example.com",
    name: "Putri Maharani",
    headline: "Productivity coach & habit builder",
    expertiseSlug: "personal-development",
    bio: "Coach produktivitas yang membantu profesional membangun sistem kerja yang tenang dan konsisten.",
  },
  {
    id: "user_instructor_12",
    email: "instructor12@example.com",
    name: "Bagus Setiawan",
    headline: "Career mentor & public speaking trainer",
    expertiseSlug: "personal-development",
    bio: "Mentor karier dan pelatih public speaking. Sudah mendampingi ratusan orang naik level di karier mereka.",
  },
  // AI & Machine Learning
  {
    id: "user_instructor_13",
    email: "instructor13@example.com",
    name: "Reza Maulana",
    headline: "AI engineer | LLM apps & AI agents",
    expertiseSlug: "ai-ml",
    bio: "AI engineer yang membangun aplikasi berbasis LLM di produksi. Fokus pada tool calling, protokol integrasi seperti MCP, dan arsitektur AI agent yang andal.",
  },
  {
    id: "user_instructor_14",
    email: "instructor14@example.com",
    name: "Citra Permata",
    headline: "AI practitioner | prompt engineering & AI-assisted dev",
    expertiseSlug: "ai-ml",
    bio: "Praktisi AI yang fokus pada prompt engineering dan pengembangan dengan bantuan AI. Senang membahas cara memakai LLM secara produktif tanpa kehilangan kontrol atas kualitas kode.",
  },
  // Product & Engineering
  {
    id: "user_instructor_15",
    email: "instructor15@example.com",
    name: "Yoga Saputra",
    headline: "Application security engineer | AppSec & secure coding",
    expertiseSlug: "product-engineering",
    bio: "Application security engineer yang sehari-hari melakukan threat modeling dan code review keamanan. Berpengalaman menutup celah OWASP Top 10 di aplikasi web skala besar.",
  },
];

export type SeedCourse = {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  categorySlug: string;
  instructorId: string;
  level: CourseLevel;
  price: number;
  status: CourseStatus;
  publishedAt: Date | null;
  topic: string;
};

const md = (paras: string[]) => paras.join("\n\n");

export const COURSES: SeedCourse[] = [
  {
    id: "course_api_testing",
    slug: "api-testing-postman",
    title: "Belajar API Testing dengan Postman dari Nol",
    subtitle: "Uji REST API secara sistematis tanpa menulis banyak kode",
    description: md([
      "Kursus ini membawamu memahami API testing dari dasar menggunakan Postman. Kamu akan belajar membaca dokumentasi API, membuat request, hingga menyusun koleksi tes yang rapi.",
      "Di akhir kelas kamu bisa membuat automated test sederhana, menjalankan koleksi lewat Collection Runner, dan memvalidasi response API dengan percaya diri.",
    ]),
    categorySlug: "programming",
    instructorId: "user_instructor",
    level: CourseLevel.INTERMEDIATE,
    price: 249000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-20T00:00:00.000Z"),
    topic: "API Testing",
  },
  {
    id: "course_nextjs_pemula",
    slug: "next-js-14-untuk-pemula",
    title: "Next.js 14 untuk Pemula",
    subtitle: "Bangun aplikasi web full-stack dengan App Router",
    description: md([
      "Pelajari Next.js 14 dari nol: routing dengan App Router, Server Components, dan pengambilan data di sisi server.",
      "Kamu akan membangun beberapa halaman nyata sambil memahami kapan memakai Server Component vs Client Component.",
    ]),
    categorySlug: "programming",
    instructorId: "user_instructor",
    level: CourseLevel.BEGINNER,
    price: 0,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-06-01T00:00:00.000Z"),
    topic: "Next.js",
  },
  {
    id: "course_typescript",
    slug: "typescript-mendalam",
    title: "TypeScript Mendalam",
    subtitle: "Type system, generics, dan pattern lanjutan",
    description: md([
      "Tingkatkan pemahaman TypeScript-mu: dari tipe dasar ke generics, utility types, dan pattern yang dipakai di codebase production.",
      "Cocok untuk developer yang sudah pakai TypeScript tapi ingin menulis tipe yang lebih aman dan ekspresif.",
    ]),
    categorySlug: "programming",
    instructorId: "user_instructor",
    level: CourseLevel.ADVANCED,
    price: 349000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-04-10T00:00:00.000Z"),
    topic: "TypeScript",
  },
  {
    id: "course_ui_fundamentals",
    slug: "ui-design-fundamentals",
    title: "UI Design Fundamentals: dari Wireframe ke High-Fidelity",
    subtitle: "Prinsip antarmuka yang rapi, konsisten, dan mudah dipakai",
    description: md([
      "Mulai dari prinsip dasar desain antarmuka: layout, tipografi, warna, dan spacing. Kamu akan berlatih dari wireframe sampai high-fidelity mockup.",
      "Kelas ini membangun fondasi yang kuat sebelum kamu mendalami tools desain yang lebih advanced.",
    ]),
    categorySlug: "design",
    instructorId: "user_instructor_2",
    level: CourseLevel.BEGINNER,
    price: 199000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-05T00:00:00.000Z"),
    topic: "UI Design",
  },
  {
    id: "course_figma",
    slug: "figma-untuk-product-designer",
    title: "Figma untuk Product Designer",
    subtitle: "Workflow desain produk modern di Figma",
    description: md([
      "Kuasai Figma sebagai tool utama product designer: components, auto layout, variants, dan prototyping.",
      "Kamu akan belajar menyusun file yang rapi dan mudah di-handoff ke tim engineering.",
    ]),
    categorySlug: "design",
    instructorId: "user_instructor_2",
    level: CourseLevel.INTERMEDIATE,
    price: 0,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-28T00:00:00.000Z"),
    topic: "Figma",
  },
  {
    id: "course_design_system",
    slug: "design-system-dari-nol",
    title: "Design System dari Nol",
    subtitle: "Bangun design system yang scalable dan konsisten",
    description: md([
      "Pelajari cara membangun design system: tokens, komponen, dokumentasi, dan governance.",
      "Kelas ini masih dalam penyusunan dan akan segera dirilis.",
    ]),
    categorySlug: "design",
    instructorId: "user_instructor_2",
    level: CourseLevel.ADVANCED,
    price: 449000,
    status: CourseStatus.DRAFT,
    publishedAt: null,
    topic: "Design System",
  },
  {
    id: "course_excel",
    slug: "excel-analisis-bisnis",
    title: "Excel untuk Analisis Bisnis",
    subtitle: "Olah dan analisis data bisnis dengan Excel",
    description: md([
      "Belajar Excel untuk kebutuhan bisnis nyata: formula penting, PivotTable, dan dashboard sederhana.",
      "Setelah kelas ini kamu bisa mengubah data mentah jadi laporan yang mudah dibaca.",
    ]),
    categorySlug: "data-analytics",
    instructorId: "user_instructor_3",
    level: CourseLevel.BEGINNER,
    price: 149000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-03-15T00:00:00.000Z"),
    topic: "Excel",
  },
  {
    id: "course_sql",
    slug: "sql-untuk-data-analyst",
    title: "SQL untuk Data Analyst",
    subtitle: "Query, join, dan agregasi data dengan SQL",
    description: md([
      "Kuasai SQL untuk analisis data: SELECT, filtering, JOIN antar tabel, agregasi, dan subquery.",
      "Kamu akan banyak berlatih dengan studi kasus dataset yang realistis.",
    ]),
    categorySlug: "data-analytics",
    instructorId: "user_instructor_3",
    level: CourseLevel.INTERMEDIATE,
    price: 299000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-04-22T00:00:00.000Z"),
    topic: "SQL",
  },
  {
    id: "course_dataviz",
    slug: "dasar-data-visualization",
    title: "Dasar Data Visualization",
    subtitle: "Sajikan data jadi cerita yang mudah dipahami",
    description: md([
      "Pelajari prinsip visualisasi data: memilih chart yang tepat, menghindari grafik yang menyesatkan, dan bercerita lewat data.",
      "Cocok untuk siapa saja yang sering presentasi angka ke audiens.",
    ]),
    categorySlug: "data-analytics",
    instructorId: "user_instructor_3",
    level: CourseLevel.BEGINNER,
    price: 0,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-06-03T00:00:00.000Z"),
    topic: "Data Visualization",
  },
  {
    id: "course_digital_marketing",
    slug: "digital-marketing-umkm",
    title: "Digital Marketing untuk UMKM",
    subtitle: "Strategi pemasaran digital praktis untuk usaha kecil",
    description: md([
      "Strategi digital marketing yang langsung bisa dipakai UMKM: konten media sosial, iklan dasar, dan funnel sederhana.",
      "Fokus pada langkah praktis dengan budget terbatas namun terukur.",
    ]),
    categorySlug: "business",
    instructorId: "user_instructor_4",
    level: CourseLevel.BEGINNER,
    price: 179000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-12T00:00:00.000Z"),
    topic: "Digital Marketing",
  },
  {
    id: "course_product_mgmt",
    slug: "manajemen-produk-pemula",
    title: "Manajemen Produk untuk Pemula",
    subtitle: "Dari ide ke roadmap produk",
    description: md([
      "Pengantar manajemen produk: menemukan masalah, memprioritaskan fitur, dan menyusun roadmap.",
      "Kelas ini sudah diarsipkan dan digantikan versi yang lebih baru.",
    ]),
    categorySlug: "business",
    instructorId: "user_instructor_4",
    level: CourseLevel.INTERMEDIATE,
    price: 329000,
    status: CourseStatus.ARCHIVED,
    publishedAt: new Date("2026-02-10T00:00:00.000Z"),
    topic: "Manajemen Produk",
  },
  {
    id: "course_produktivitas",
    slug: "produktivitas-manajemen-waktu",
    title: "Produktivitas & Manajemen Waktu",
    subtitle: "Sistem sederhana untuk fokus dan konsisten",
    description: md([
      "Bangun sistem produktivitas pribadi: prioritas, time blocking, dan kebiasaan yang berkelanjutan.",
      "Bukan soal sibuk, tapi soal mengerjakan hal yang benar dengan tenang.",
    ]),
    categorySlug: "personal-development",
    instructorId: "user_instructor_4",
    level: CourseLevel.BEGINNER,
    price: 0,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-30T00:00:00.000Z"),
    topic: "Manajemen Waktu",
  },

  // ==========================================
  // AI & Engineering expansion (new content)
  // ==========================================
  {
    id: "course_mcp",
    slug: "mcp-untuk-developer",
    title: "MCP (Model Context Protocol) untuk Developer",
    subtitle: "Hubungkan aplikasi AI ke tool & data lewat satu protokol standar",
    description: md([
      "Model Context Protocol (MCP) adalah protokol terbuka yang menstandarkan cara aplikasi AI terhubung ke sumber data dan tool eksternal. Alih-alih menulis integrasi khusus untuk setiap model, kamu cukup membangun satu MCP server yang mengekspos tools, resources, dan prompts lewat antarmuka berbasis JSON-RPC.",
      "Di kelas ini kamu akan memahami arsitektur client–server MCP, membangun MCP server sendiri menggunakan SDK resmi, dan menghubungkannya ke host seperti Claude Desktop atau IDE. Kamu juga belajar memilih transport yang tepat — stdio untuk integrasi lokal, HTTP/SSE untuk server remote.",
      "Setelah menyelesaikan kursus, kamu bisa memaketkan kapabilitas internal tim — database, API internal, atau dokumentasi — sebagai MCP server yang reusable, sehingga asisten AI dapat memakainya secara aman dan konsisten.",
    ]),
    categorySlug: "ai-ml",
    instructorId: "user_instructor_13",
    level: CourseLevel.INTERMEDIATE,
    price: 349000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-06-08T00:00:00.000Z"),
    topic: "MCP",
  },
  {
    id: "course_rag",
    slug: "rag-retrieval-augmented-generation",
    title: "RAG & Search: Membangun Retrieval-Augmented Generation",
    subtitle: "Jawaban LLM yang akurat dan terlacak di atas data milikmu",
    description: md([
      "Retrieval-Augmented Generation (RAG) menggabungkan kekuatan large language model dengan basis pengetahuanmu sendiri. Alih-alih mengandalkan ingatan model yang bisa usang atau berhalusinasi, RAG mengambil potongan dokumen yang relevan lalu menyuntikkannya ke dalam prompt sebagai konteks.",
      "Kamu akan membangun pipeline RAG end-to-end: chunking dokumen, membuat embeddings, menyimpannya di vector database, lalu melakukan similarity search untuk menemukan konteks paling relevan sebelum model menjawab. Kita juga membahas teknik meningkatkan kualitas retrieval seperti hybrid search dan re-ranking.",
      "Di akhir kelas kamu mampu membuat aplikasi tanya-jawab di atas data privat — dokumentasi internal, knowledge base, atau katalog produk — yang jawabannya akurat dan dapat dilacak sumbernya.",
    ]),
    categorySlug: "ai-ml",
    instructorId: "user_instructor_9",
    level: CourseLevel.INTERMEDIATE,
    price: 399000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-25T00:00:00.000Z"),
    topic: "RAG",
  },
  {
    id: "course_ml_fundamentals",
    slug: "machine-learning-fundamentals",
    title: "Machine Learning Fundamentals",
    subtitle: "Bangun intuisi ML yang benar, dari data ke model pertama",
    description: md([
      "Pahami fondasi machine learning tanpa terjebak matematika yang menakutkan. Kamu akan mengenal perbedaan supervised dan unsupervised learning, serta alur kerja standar: menyiapkan data, melatih model, dan mengevaluasinya.",
      "Lewat latihan dengan Python dan scikit-learn, kamu membangun model klasifikasi dan regresi sederhana, lalu belajar membaca metrik evaluasi seperti accuracy, precision, dan recall — sekaligus memahami masalah overfitting lewat train/test split dan cross-validation.",
      "Kelas ini cocok sebagai langkah pertama sebelum mendalami deep learning atau MLOps. Fokusnya membangun intuisi yang benar, bukan menghafal algoritma.",
    ]),
    categorySlug: "ai-ml",
    instructorId: "user_instructor_8",
    level: CourseLevel.BEGINNER,
    price: 0,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-04-18T00:00:00.000Z"),
    topic: "Machine Learning",
  },
  {
    id: "course_appsec",
    slug: "application-security-untuk-developer",
    title: "Application Security untuk Developer",
    subtitle: "Tulis kode yang tahan serangan dengan mindset penyerang",
    description: md([
      "Keamanan bukan hanya tanggung jawab tim security — developer adalah garis pertahanan pertama. Kursus ini mengajarkan cara berpikir seperti penyerang agar kamu bisa menulis kode yang tahan terhadap serangan umum.",
      "Kita bedah OWASP Top 10 dengan contoh nyata: injection (SQL & command), Cross-Site Scripting (XSS), broken authentication, hingga insecure deserialization. Untuk tiap kategori kamu belajar mendeteksi celahnya dan pola mitigasi yang benar — validasi input, parameterized query, output encoding, dan manajemen secret.",
      "Kamu juga akan mengenal dasar threat modeling dan cara mengintegrasikan pemeriksaan keamanan seperti dependency scanning dan SAST ke dalam workflow sehari-hari.",
    ]),
    categorySlug: "product-engineering",
    instructorId: "user_instructor_15",
    level: CourseLevel.INTERMEDIATE,
    price: 379000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-15T00:00:00.000Z"),
    topic: "Application Security",
  },
  {
    id: "course_system_design",
    slug: "system-design-interview-preparation",
    title: "System Design Interview Preparation",
    subtitle: "Kerangka merancang sistem skala besar di bawah tekanan interview",
    description: md([
      "Persiapkan dirimu menghadapi interview system design yang sering jadi penentu di posisi senior. Kursus ini memberi kerangka berpikir terstruktur untuk merancang sistem berskala besar di bawah tekanan waktu.",
      "Kamu akan menguasai building block penting: load balancing, caching, replikasi dan sharding database, message queue, serta trade-off konsistensi vs ketersediaan (CAP theorem). Setiap konsep dibahas lewat studi kasus nyata seperti merancang URL shortener, news feed, dan sistem chat.",
      "Lebih dari sekadar teori, kamu belajar mengomunikasikan keputusan desain, mengklarifikasi requirement, dan memperkirakan kapasitas — skill yang benar-benar dinilai pewawancara.",
    ]),
    categorySlug: "product-engineering",
    instructorId: "user_instructor_5",
    level: CourseLevel.ADVANCED,
    price: 449000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-03-28T00:00:00.000Z"),
    topic: "System Design",
  },
  {
    id: "course_agentic_ai",
    slug: "agentic-ai-membangun-ai-agents",
    title: "Agentic AI: Membangun AI Agents",
    subtitle: "Agent yang merencanakan, memakai tools, dan bertindak mandiri",
    description: md([
      "AI agent adalah sistem yang tidak hanya menjawab, tapi merencanakan dan mengambil tindakan untuk mencapai tujuan. Di kursus ini kamu akan membangun agent yang bisa memakai tools, mengingat konteks, dan menyelesaikan tugas multi-langkah secara mandiri.",
      "Kamu mempelajari pola inti agentic seperti loop reasoning-and-acting (ReAct), tool/function calling, manajemen memori, dan orkestrasi multi-agent. Kita juga membahas hal krusial di produksi: menangani kegagalan tool, membatasi loop, dan menjaga agent tetap pada jalurnya.",
      "Kelas ini menuntut pemahaman dasar tentang LLM dan API. Setelah selesai, kamu mampu merancang agent yang berguna sekaligus aman dan dapat diprediksi.",
    ]),
    categorySlug: "ai-ml",
    instructorId: "user_instructor_13",
    level: CourseLevel.ADVANCED,
    price: 429000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-06-10T00:00:00.000Z"),
    topic: "Agentic AI",
  },
  {
    id: "course_vibe_coding",
    slug: "vibe-coding-produktif-dengan-ai",
    title: "Vibe Coding: Produktif dengan AI Coding Tools",
    subtitle: "Delegasikan pengetikan kode ke AI, tetap pegang kendali kualitas",
    description: md([
      "Vibe coding adalah cara baru membangun software dengan mendelegasikan sebagian besar pengetikan kode ke AI, sementara kamu fokus pada arah, konteks, dan keputusan. Kursus ini mengajarkan cara memakai AI coding tools modern — asisten di editor maupun CLI — secara produktif.",
      "Kamu akan belajar memberi konteks yang tepat, memecah tugas jadi langkah yang bisa dikerjakan AI, lalu mereview dan memverifikasi hasilnya secara kritis. Kita tekankan bahwa AI mempercepat pekerjaan, bukan menggantikan tanggung jawabmu atas kualitas dan keamanan kode.",
      "Cocok untuk developer maupun pemula yang ingin bekerja lebih cepat tanpa kehilangan pemahaman atas apa yang sedang dibangun.",
    ]),
    categorySlug: "product-engineering",
    instructorId: "user_instructor_14",
    level: CourseLevel.BEGINNER,
    price: 0,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-06-05T00:00:00.000Z"),
    topic: "Vibe Coding",
  },
  {
    id: "course_figma_ui",
    slug: "figma-untuk-ui-designer",
    title: "Figma untuk UI Designer",
    subtitle: "Bangun antarmuka rapi dan siap di-handoff dengan cepat",
    description: md([
      "Fokus penuh pada pembuatan antarmuka yang rapi dan siap diimplementasikan. Berbeda dari kelas desain umum, kursus ini membahas Figma dari sudut pandang UI designer yang mengejar konsistensi dan kecepatan.",
      "Kamu akan menguasai auto layout, components dan variants, styles, hingga variables untuk membangun UI kit dan design system kecil. Kita juga melatih layout responsif dan cara menata file agar mudah di-handoff ke developer.",
      "Lewat proyek membangun beberapa layar produk nyata, kamu terbiasa bekerja cepat namun tetap presisi — dari komponen tombol sampai halaman penuh.",
    ]),
    categorySlug: "design",
    instructorId: "user_instructor_7",
    level: CourseLevel.BEGINNER,
    price: 199000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-04-30T00:00:00.000Z"),
    topic: "Figma",
  },
  {
    id: "course_prompt_engineering",
    slug: "prompt-engineering-untuk-llm",
    title: "Prompt Engineering untuk LLM",
    subtitle: "Rancang instruksi yang membuat output AI akurat dan konsisten",
    description: md([
      "Prompt engineering adalah keterampilan merancang instruksi agar large language model memberi hasil yang akurat dan konsisten. Kursus ini membongkar pola-pola yang terbukti efektif, bukan sekadar trik.",
      "Kamu akan belajar menyusun system prompt yang jelas, memakai few-shot examples, memandu penalaran lewat chain-of-thought, dan meminta output terstruktur seperti JSON yang mudah diproses program. Kita juga membahas cara mengiterasi dan mengevaluasi prompt secara sistematis.",
      "Materi bersifat tool-agnostic sehingga teknik yang kamu pelajari bisa dipakai di berbagai model. Cocok untuk siapa saja yang bekerja dengan AI setiap hari.",
    ]),
    categorySlug: "ai-ml",
    instructorId: "user_instructor_14",
    level: CourseLevel.BEGINNER,
    price: 0,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-09T00:00:00.000Z"),
    topic: "Prompt Engineering",
  },
  {
    id: "course_flutter",
    slug: "flutter-aplikasi-mobile-pertama",
    title: "Flutter: Bangun Aplikasi Mobile Pertamamu",
    subtitle: "Satu basis kode untuk Android dan iOS",
    description: md([
      "Bangun aplikasi mobile lintas platform pertamamu dengan Flutter. Dari satu basis kode, kamu bisa merilis aplikasi untuk Android dan iOS sekaligus.",
      "Kamu akan belajar widget, layout, navigasi antar halaman, dan state management dasar sambil membangun aplikasi nyata langkah demi langkah.",
    ]),
    categorySlug: "programming",
    instructorId: "user_instructor_6",
    level: CourseLevel.BEGINNER,
    price: 229000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-03-20T00:00:00.000Z"),
    topic: "Flutter",
  },
  {
    id: "course_startup_validation",
    slug: "validasi-ide-startup",
    title: "Validasi Ide Startup & Pertumbuhan Awal",
    subtitle: "Uji idemu sebelum menghabiskan waktu dan modal",
    description: md([
      "Sebelum menulis banyak kode atau menghabiskan modal, validasi dulu apakah idemu memang dibutuhkan pasar. Kursus ini membahas cara menguji asumsi dengan cepat dan murah.",
      "Kamu akan belajar merumuskan hipotesis, melakukan wawancara pelanggan, membangun MVP sederhana, dan membaca sinyal awal pertumbuhan untuk memutuskan lanjut atau pivot.",
    ]),
    categorySlug: "business",
    instructorId: "user_instructor_10",
    level: CourseLevel.INTERMEDIATE,
    price: 269000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-04-02T00:00:00.000Z"),
    topic: "Validasi Startup",
  },
  {
    id: "course_deep_work",
    slug: "deep-work-fokus-di-era-distraksi",
    title: "Deep Work: Fokus di Era Distraksi",
    subtitle: "Bangun kebiasaan fokus dalam yang berkelanjutan",
    description: md([
      "Di tengah notifikasi yang tak ada habisnya, kemampuan fokus dalam jadi keunggulan langka. Kursus ini membantumu membangun kebiasaan deep work yang berkelanjutan.",
      "Kamu akan belajar merancang blok waktu fokus, mengelola distraksi digital, dan menjaga energi agar bisa menghasilkan kerja berkualitas tanpa kelelahan.",
    ]),
    categorySlug: "personal-development",
    instructorId: "user_instructor_11",
    level: CourseLevel.BEGINNER,
    price: 0,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-05-18T00:00:00.000Z"),
    topic: "Deep Work",
  },
  {
    id: "course_public_speaking",
    slug: "public-speaking-untuk-profesional",
    title: "Public Speaking untuk Profesional",
    subtitle: "Tampil percaya diri dan sampaikan pesan dengan jelas",
    description: md([
      "Kemampuan berbicara di depan publik bisa dilatih, bukan bakat bawaan. Kursus ini membekalimu teknik praktis untuk tampil percaya diri dan menyampaikan pesan dengan jelas.",
      "Dari menyusun struktur presentasi, mengelola gugup, hingga membaca audiens — kamu akan berlatih lewat contoh dan tips yang langsung bisa dipraktikkan di rapat maupun panggung.",
    ]),
    categorySlug: "personal-development",
    instructorId: "user_instructor_12",
    level: CourseLevel.BEGINNER,
    price: 159000,
    status: CourseStatus.PUBLISHED,
    publishedAt: new Date("2026-02-25T00:00:00.000Z"),
    topic: "Public Speaking",
  },
];

/**
 * Short, curated keyword per course for the generated 3D cover (not the full
 * title). Keyed by course id. Falls back to the title if a course is missing.
 */
export const COVER_LABELS: Record<string, string> = {
  course_api_testing: "API",
  course_nextjs_pemula: "Next.js",
  course_typescript: "TypeScript",
  course_ui_fundamentals: "UI Design",
  course_figma: "Figma",
  course_design_system: "Design System",
  course_excel: "Excel",
  course_sql: "SQL",
  course_dataviz: "Data Viz",
  course_digital_marketing: "Marketing",
  course_product_mgmt: "Product",
  course_produktivitas: "Productivity",
  course_mcp: "MCP",
  course_rag: "RAG",
  course_ml_fundamentals: "Machine Learning",
  course_appsec: "Security",
  course_system_design: "System Design",
  course_agentic_ai: "Agentic AI",
  course_vibe_coding: "Vibe Coding",
  course_figma_ui: "Figma",
  course_prompt_engineering: "Prompt Engineering",
  course_flutter: "Flutter",
  course_startup_validation: "Startup",
  course_deep_work: "Deep Work",
  course_public_speaking: "Public Speaking",
};
